[camera]
index = 0
format = "RGB888"
width = 1024
height = 768

[network]
video_port = "1580"
data_port = "2024"
host = "192.168.1.11"

[models]
gestures_model = "../models/gestures2.mdl"
gestures_labels = "../models/жесты.csv"
emotions_model = "../models/emotions2.mdl"
emotions_labels = "../models/эмоции.csv"

[servos.16]
min = 1200
max = 1600
value = 1500
reverse = true
name = "Подъём головы"

[servos.17]
min = 1000
max = 2100
value = 1550
reverse = true
name = "Поворот шеи"

[servos.18]
min = 500
max = 2500
value = 1500
name = "Поворот правого плеча"

[servos.19]
min = 1500
max = 2400
value = 1500
name = "Подъём правого плеча"

[servos.20]
min = 1500
max = 2400
value = 1500
name = "Сгибание правого локтя"

[servos.21]
min = 1200
max = 1500
value = 1200
reverse = true
name = "Сгибание правого мизинца"

[servos.23]
min = 1200
max = 1500
value = 1200
reverse = true
name = "Сгибание правого безымянного пальца"

[servos.22]
min = 1300
max = 1750
value = 1300
name = "Сгибание правого среднего пальца"

[servos.24]
min = 1400
max = 1800
value = 1400
name = "Сгибание правого указательного пальца"

[servos.25]
min = 1100
max = 1800
value = 1100
name = "Сгибание правого большого пальца"

[servos.26]
min = 800
max = 1500
value = 800
reverse = true
name = "Отведение правой ноги"

[servos.27]
min = 600
max = 2400
value = 600
reverse = true
name = "Подъём правой ноги"

[servos.28]
min = 1500
max = 2400
value = 1500
name = "Сгибание правого колена"

[servos.29]
min = 1200
max = 2500
value = 1200
reverse = true
name = "Сгибание правой ступни"

[servos.30]
min = 1000
max = 2000
value = 1500
reverse = true
name = "Наклон правой ступни"

[servos.15]
min = 500
max = 2500
value = 1500
name = "Поворот левого плеча"

[servos.14]
min = 500
max = 1400
value = 500
reverse = true
name = "Подъём левого плеча"

[servos.13]
min = 500
max = 1400
value = 500
reverse = true
name = "Сгибание левого локтя"

[servos.11]
min = 1200
max = 1700
value = 1200
name = "Сгибание левого мизинца"

[servos.12]
min = 1300
max = 1700
value = 1300
name = "Сгибание левого безымянного пальца"

[servos.10]
min = 1300
max = 1700
value = 1300
reverse = true
name = "Сгибание левого среднего пальца"

[servos.9]
min = 1100
max = 1650
value = 1100
reverse = true
name = "Сгибание левого указательного пальца"

[servos.8]
min = 1100
max = 1500
value = 1100
reverse = true
name = "Сгибание левого большого пальца"

[servos.7]
min = 1500
max = 2500
value = 1500
name = "Отведение левой ноги"

[servos.6]
min = 600
max = 2400
value = 1500
name = "Подъём левой ноги"

[servos.5]
min = 400
max = 1500
value = 1500
reverse = true
name = "Сгибание левого колена"

[servos.4]
min = 1000
max = 1500
value = 1500
reverse = true
name = "Сгибание левой ступни"

[servos.3]
min = 1000
max = 2000
value = 1500
reverse = true
name = "Наклон левой ступни"
